module.exports = {
  COOKIE: 'JSESSIONID=66F71E8A37E6876EF50BAC43597209A1',
  EXCLUDES: [
    'mirserver111-去去去',
    'mirservergdcs1-更多游戏请加群',
    // "mirserverwzzd-无主大神器",
    // "mirserveryw-创世遗忘",
    'mirservergdcs-鬼帝传说',
    'mirserverjycm-金庸专属神器',
    // "mirservergdzw-一万多级超变",
    // "mirserverwsms-武神迷失",
    // "mirserverwxhl-一刀999999999+",
    // "mirserverdjp-超大极品",
    // "mirservertzms-天之迷失",
    // "mirservertx1-宝宝专属",
    // "mirservertx2-新宝宝专属[第二季]",
    // "mirservergdcs-鬼帝传说",
    // "mirserveryw-创世遗忘",
    'mirserverwzzd-无主大神器',
    // "mirserverezss-杀神无限刀",
    // "mirserverfsl-封神录",
    // "mirserveryjzz-异界之战",
  ],
  MERGE_EXCLUDE: [
    'mirserver111-去去去',
    'mirservergdcs1-更多游戏请加群',
    // "mirserverwzzd-无主大神器",
    // "mirserveryw-创世遗忘",
    // "mirservergdcs-鬼帝传说",
    // "mirserverjycm-金庸专属神器",
    // "mirservergdzw-一万多级超变",
    // "mirserverwsms-武神迷失",
    // "mirserverwxhl-一刀999999999+",
    // "mirserverdjp-超大极品",
    // "mirservertzms-天之迷失",
    // "mirservertx1-宝宝专属",
    // "mirservertx2-新宝宝专属[第二季]",
    // "mirservergdcs-鬼帝传说",
    // "mirserveryw-创世遗忘",
    // "mirserverwzzd-无主大神器",
    // "mirserverezss-杀神无限刀",
    // "mirserverfsl-封神录",
    // "mirserveryjzz-异界之战",
  ],
};
